project:
  type: website
  pre-render: tools/make_bsdd_import_json.py
  post-render: "cp tools/bsdd-import-bdns.json _site/bsdd-import-bdns.json"

website:
  repo-url: https://github.com/theodi/BDNS
  repo-actions: [edit, source, issue]
  navbar:

    left:
      - href: index.qmd
      - href: BDNS_Governance_model.md
        text: Governance
      - href: BDNS_Scoping_guidelines_and_principles.md
        text: Scope
      - href: BDNS_Specification_naming_syntax.md
        text: Naming Specification Syntax
      - href: BDNS_Abbreviations_Register.qmd
        text: Abbreviations Register
      - href: BDNS_Abbreviations_Systems.qmd
        text: Systems Abbreviations
      - href: BDNS_Abbreviations_Core.qmd
        text: Abbreviations Core
      - href: BDNS_BSDD.qmd
        text: BDNS on BSDD

    right:
      - icon: github
        href: https://github.com/theodi/BDNS
        aria-label: GitHub

format:
  html:
    css: styles.css
    toc: true
    theme:
      light: flatly
      dark: darkly


